on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: booklet

jobs:
  bookdown:
    name: build-and-deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - name: Install pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install tinyTeX
        uses: r-lib/actions/setup-tinytex@v2

      - name: Install System Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y curl libcurl4-doc libcurl4-openssl-dev \
            libharfbuzz-dev libfribidi-dev libmagick++-dev libpoppler-cpp-dev

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2

      - name: Render book HTML
        run: |
          Rscript -e 'bookdown::clean_book(TRUE)'
          Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::gitbook")'

      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          email: ${{ secrets.EMAIL }}      # must be a verified email
          build_dir: _book/                # "_site/" by default
